---
title: '225A Workshop 2: RStudio and Tidyverse'
author: "Nicholas Carey"
date: "2023-10-12"
output:
  html_document:
    df_print: paged
---

I can type like this!

```{r load_packages}
library(tidyverse)
```

Cmd (Cntrl) + Option (Alt) + I inserts a new chunk!
```{r Read in Data}
sf_weather <- read.csv("../raw_data/sf_weather_2023.csv")
head(sf_weather)
colnames(sf_weather)
```

```{r Subset the data}
sf_weather %>% 
  select(DATE)
date <- sf_weather %>% 
  select(DATE)
```

```{r Subset the data and split out data}
sf_weather_temps <- sf_weather %>% 
  select(c(DATE,TMAX,TMIN)) %>% 
  na.omit() %>% 
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = F) %>% 
  filter(YEAR == "2021") %>% #double == for filter
  mutate(TAVG = ((TMAX+TMIN)/2)) %>% #single = to assign a new column
  group_by(MONTH) %>% 
  summarise(MAX_MO_TEMP = max(TAVG))

sf_weather_temps
```

```{r Plotting out data}
plot(sf_weather_temps)
```

```{r Make a function to subset data}
yearly_subsetter <- function(year){
  year_subset <- sf_weather %>% 
    select(c(DATE,TMAX,TMIN)) %>% 
    na.omit() %>% 
    separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = F) %>% 
    filter(YEAR == year) %>% #double == for filter
    mutate(TAVG = ((TMAX+TMIN)/2)) %>% #single = to assign a new column
    group_by(MONTH) %>% 
    summarise(MAX_MO_TEMP = max(TAVG))
  
  year_subset
}
```

```{r apply function to date}
year <- "1980"

plot(yearly_subsetter(year), main = year)
```

```{r Inspect several years at once with a loop, fig.width=6, fig.height=4}
for ( year in c("1970", "1980", "1990", "2000") ) {
  plot(yearly_subsetter(year), main = year)
}
```

